# Generated by Django 4.0.4 on 2022-09-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
    ]
